### ISSUE TITLE
No remote found for dependency "jashkenas/backbone@1.3.3"

### ISSUE THREAD

**Issue by mohangandhiGH** [laidig/gtfs-validator#6]
While trying to build the laidig_webapp, using command 'component build', it is giving an error saying that there is no remote dependency found for latest version of jashkenas/backbone

**Comment by laidig** [comment]
Component has apparently been deprecated (yay JS ecosystem!), so this might be the cause. I don't know, as I'm not familiar with it.

Would anyone like to volunteer to take this on?

**Comment by mohangandhiGH** [comment]
I think there is no remote dependency for jashkenas/backbone from version 1.3.0 and above. I tried with the version before 1.3.0 i.e., 1.2.3 and able to find dependency for this version in component repository.
 So, atleast for now, we can modify component.json file to use jashkenas/backbone version 1.2.3

**Comment by laidig** [comment]
PRs gladly accepted ;)
